#!/bin/bash

#set path to installed node modules when this script is run without npm 
PATH=$PATH:./node_modules/.bin

#ndjson args
NDJSON_ARGS="(delete d.properties, d)"


if [ -n "$1" ] 
  then 
    if [[ "$1" == "-n" || "$1" == "--with-names" ]]
      then
        NDJSON_ARGS="(d.name=d.properties.NAMEUNIT, delete d.properties, d)"
        echo 'Working'
    fi
fi

# Simplification
SP=0.0001

# Quantization
QU=1e4

rm -rvf es
mkdir -p build es

curl -o build/lineas_limite.zip -C - 'http://centrodedescargas.cnig.es/CentroDescargas/equipamiento/lineas_limite.zip'
unzip -jod build build/lineas_limite.zip recintos_municipales* recintos_provinciales*

geo2topo -n provinces=<( \
    shp2json --encoding utf8 -n build/recintos_provinciales_inspire_peninbal_etrs89.shp \
      | ndjson-map '(d.id = d.properties.NATCODE.slice(4, 6), d)'
    shp2json --encoding utf8 -n build/recintos_provinciales_inspire_canarias_wgs84.shp \
      | ndjson-map '(d.id = d.properties.NATCODE.slice(4, 6), d)') \
  | toposimplify -f -p $SP \
  | topomerge autonomous_regions=provinces -k 'd.properties.NATCODE.slice(2, 4)' \
  | topomerge nation=autonomous_regions \
  > es/provinces.json

geo2topo -n municipalities=<( \
    shp2json --encoding utf8 -n build/recintos_municipales_inspire_peninbal_etrs89.shp \
      | ndjson-map '(d.id = d.properties.NATCODE.slice(6, 11), d)'
    shp2json --encoding utf8 -n build/recintos_municipales_inspire_canarias_wgs84.shp \
      | ndjson-map '(d.id = d.properties.NATCODE.slice(6, 11), d)') \
  | toposimplify -f -p $SP \
  | topomerge provinces=municipalities -k 'd.properties.NATCODE.slice(4, 6)' \
  | topomerge autonomous_regions=municipalities -k 'd.properties.NATCODE.slice(2, 4)' \
  | topomerge nation=autonomous_regions \
  > es/municipalities.json

# Inspired by: https://bl.ocks.org/mbostock/39b34968ad5eab65de1d7da81f78bb27
# Re-compute the topology as a further optimization.
# This consolidates unique sequences of arcs.
# https://github.com/topojson/topojson-simplify/issues/4
topo2geo -n \
  < es/provinces.json \
  provinces=es/_provinces.json \
  autonomous_regions=es/_autonomous_regions.json \
  nation=es/_nation.json

geo2topo -n \
  provinces=<( \
      cat es/_provinces.json \
        | ndjson-map "$NDJSON_ARGS") \
  autonomous_regions=<( \
      cat es/_autonomous_regions.json \
        | ndjson-map "$NDJSON_ARGS") \
  nation=<( \
      cat es/_nation.json \
        | ndjson-map "$NDJSON_ARGS") \
  | topoquantize $QU \
  > es/provinces.json

rm es/_provinces.json es/_autonomous_regions.json es/_nation.json

topo2geo -n \
  < es/municipalities.json \
  municipalities=es/_municipalities.json \
  provinces=es/_provinces.json \
  autonomous_regions=es/_autonomous_regions.json \
  nation=es/_nation.json
  
geo2topo -n \
  municipalities=<( \
      cat es/_municipalities.json \
        | ndjson-map "$NDJSON_ARGS") \
  provinces=<( \
      cat es/_provinces.json \
        | ndjson-map "$NDJSON_ARGS") \
  autonomous_regions=<( \
      cat es/_autonomous_regions.json \
        | ndjson-map "$NDJSON_ARGS") \
  nation=<( \
      cat es/_nation.json \
        | ndjson-map "$NDJSON_ARGS") \
  | topoquantize $QU \
  > es/municipalities.json

rm es/_municipalities.json es/_provinces.json es/_autonomous_regions.json es/_nation.json
